### ISSUE TITLE
Dehashed API

### ISSUE THREAD

**Issue by 252gteam** [khast3x/h8mail#99] opened 2020-09-05 15:58 UTC
*Issues not respecting the issue template will be closed without being read, thank you.*

### Checkbox

- [x] I have thoroughly checked the answer is not in the [wiki](https://github.com/khast3x/h8mail/wiki).

### Env

* h8mail version: 2.5.4
* Python version: python3
* Operating System: kali linux

### Description

I tried to search my own email using the dahashed api
but i keep getting below error
"Can only Concatenate str (not "int")"

### What I Did

```
Command run: h8mail -t gteam@gmail.com -c h8mail_config.ini

Result: Dehashed error with gteam@gmail.com
"Can only Concatenate str (not "int")"
```

**Comment by khast3x** [comment] 2020-09-09 16:45
Hello,
I have tested the query on my side, h8mail is correctly returning data using Dehashed.  
Please double check there is no typo in your `dehashed_email` and `dehashed_key` fields in the configuration file.  
If the problem persists, please add the output with the `--debug` option, such as:
```
h8mail -t gteam@gmail.com -c h8mail_config.ini --debug
```
If the problem is solved, please close the issue.

Cheers

**Comment by 252gteam** [comment] 2020-09-11 01:29
please see my screenshot of what i am getting

![error](https://user-images.githubusercontent.com/70812772/92838299-83eb2c80-f3d6-11ea-9f5b-8e3d52882a59.PNG)

**Closed** 2020-09-11 01:31 UTC
