### ISSUE TITLE
Don't use Dehashed

### ISSUE THREAD

**Issue by BroadBandSec** [khast3x/h8mail#88] opened 2020-07-06 20:17 UTC
### Env

* h8mail version:  Version 2.5.2 - "ROCKSMASSON.2"
* Python version:  3.8.3
* Operating System:  Debian based

### Description

I wouldn't recommend Dehased.com anymore. We purchased two one-week trials on two separate accounts, never received activation, and never got a reply from their help desk asking what was going on. They haven't posted on their reddit account in over a year either.

**Comment by khast3x** [comment] 2020-07-06 20:25
Hello,

I can confirm, I have not been able to contact them since they updated they're API. Have sent multiple support tickets and emails that have not been answered.

**Comment by khast3x** [comment] 2020-07-21 03:02
Contact with Dehashed seems to have restarted. Users who had trouble contacting them should retry now.

**Comment by khast3x** [comment] 2020-08-05 22:00
Hello,

Fixed with PR #97 .
Run pip3 install --upgrade h8mail to update h8mail to the latest version (2.5.4).

Cheers!

**Closed by khast3x** 2020-08-05 22:00 UTC
Labels: dehashed
